# Generated by Django 2.1.7 on 2019-03-11 07:48

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyClassifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='pic_pred',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='pic_url',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='user_name_pic',
        ),
        migrations.AddField(
            model_name='pictures',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyClassifier.USER'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='pic_comment',
            field=models.TextField(default='no comment', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pictures',
            name='pic_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='pictures',
            name='pic_pred_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='pictures',
            name='pic_pred_props',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='pictures',
            name='pic_rate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.IntegerField(blank=True, default=100000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
