# Generated by Django 2.1.7 on 2019-03-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClassifier', '0002_auto_20190311_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='pic_rate',
            field=models.IntegerField(null=True),
        ),
    ]
