# Generated by Django 2.2 on 2019-04-27 22:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClassifier', '0004_pictures_pic_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_pic', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('disease_name', models.TextField(null=True)),
                ('disease_scientific_name', models.TextField(null=True)),
                ('disease_plants', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('disease_type', models.TextField(null=True)),
                ('disease_breif', models.TextField(null=True)),
                ('disease_symptoms', models.TextField(null=True)),
                ('disease_trigger', models.TextField(null=True)),
                ('disease_biological_control', models.TextField(null=True)),
                ('disease_chemical_control', models.TextField(null=True)),
                ('disease_preventive_mesures', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
        ),
    ]
