# Generated by Django 2.2 on 2019-04-28 00:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClassifier', '0005_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='disease_breif',
        ),
        migrations.AddField(
            model_name='disease',
            name='disease_nutshell',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
