# Generated by Django 2.2 on 2019-05-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClassifier', '0006_auto_20190428_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLANT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLANT_pic', models.ImageField(blank=True, null=True, upload_to='pictures/Plants_pictures')),
                ('PLANT_name', models.TextField(null=True)),
                ('PLANT_state', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='disease',
            name='disease_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/Diseases_pictures'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/predictions_pictures'),
        ),
    ]
