# Generated by Django 2.2 on 2019-05-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClassifier', '0007_auto_20190501_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/Predictions_pictures'),
        ),
    ]
