# Generated by Django 2.2 on 2019-05-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClassifier', '0008_auto_20190501_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='disease_type',
            field=models.TextField(choices=[('Virus', 'Virus'), ('Fungus', 'Fungus'), ('Bacteria', 'Bacteria'), ('Mite', 'Mite'), ('Insect', 'Insect'), ('Deficiency', 'Deficiency')], null=True),
        ),
    ]
