# Generated by Django 2.2 on 2019-05-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyClassifier', '0009_auto_20190501_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='disease_type',
            new_name='diseasetype',
        ),
    ]
