# Generated by Django 2.2 on 2019-05-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClassifier', '0013_auto_20190502_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pictures',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pictures',
            name='region',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
