# Generated by Django 2.2 on 2019-05-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClassifier', '0014_auto_20190502_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='arname',
            field=models.TextField(null=True),
        ),
    ]
