# Generated by Django 2.2 on 2019-06-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClassifier', '0015_plant_arname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobilenumber',
            field=models.IntegerField(blank=True, default=100000, null=True),
        ),
    ]
