# Generated by Django 2.2 on 2019-06-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyClassifier', '0017_auto_20190630_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
