# Generated by Django 2.2 on 2019-06-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyClassifier', '0018_disease_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaseplant',
            name='Disease',
        ),
        migrations.RemoveField(
            model_name='diseaseplant',
            name='PLANT',
        ),
        migrations.DeleteModel(
            name='PRODUCT',
        ),
        migrations.DeleteModel(
            name='DiseasePlant',
        ),
    ]
